# -*- coding: utf-8 -*-
"""
Created on Sun Jan  9 20:02:44 2022

@author: Lawrence
"""

import numpy as np
import pandas as pd
import PIL.Image as Image

import matplotlib.patches as patches
import matplotlib.pyplot as plt

from Globals import *

def rle_decode(rle_string,Image_size)->np.ndarray:
    """
    

    Parameters
    ----------
    rle_string : The Run Length encoding string
    Image_size : the image size in the form (w,d)

    Returns
    -------
    np.array binary mask

    """
    def convert_pos(pos_1d,Image_size):
        """
        A helper function to a 1d index position into a 
        2d position
        """
        return [pos_1d%Image_size[0],pos_1d//Image_size[1]]
    
    start_positions=[int(val) for val in rle_string.split()[::2]]
    run_lengths=[int(val) for val in rle_string.split()[1::2]]
    
    mask=np.zeros(Image_size)
    for i, start_position in enumerate(start_positions):
        for j in range(run_lengths[i]+1):
            
            x,y=convert_pos(start_position+j, Image_size)
            mask[x,y]=1
    return mask

    
def get_masks(imageId,encoding_df,Image_size):
    
    rle_strings=list(
        encoding_df[encoding_df.ImageId==imageId
                    ].EncodedPixels.dropna())
    
    mask=np.zeros([len(rle_strings)]+list(Image_size))
    
    for i,rle_string in enumerate(rle_strings):
        if rle_string!=float('nan'):
            mask[i,:,:]=rle_decode(rle_string,Image_size)
    
    return mask

def get_boxes(masks:np.ndarray):
    """
    

    Parameters
    ----------
    masks : np.ndarray
        the masks as generated by the get masks functions

    Returns
    -------
    a np.array where the 
    nth row is the bounding box coresponding to the object highlighted
    by the nth box in masks, the box are in the following format
    [x1, y1, x2, y2]

    """
    boxes=np.zeros([masks.shape[0],4])
    for i, mask in enumerate(masks):
        Y,X=np.where(mask)
        boxes[i]=[np.min(X),np.min(Y),
                  np.max(X),np.max(Y)]
    return boxes

def draw_boxes(boxes,ax=plt.gca()):
    
    for box in boxes:
        # Create a Rectangle patch
        rect = patches.Rectangle(
            (box[0], box[1]), box[2]-box[0], box[3]-box[1], 
            linewidth=1, edgecolor='r', 
            facecolor='none')

        # Add the patch to the Axes
        ax.add_patch(rect)
        

if __name__=="__main__":
    #testing
    #import matplotlib.pyplot as plt
    Data_df=pd.read_csv(f"{Data_Dir}/train_ship_segmentations_v2.csv")
    i=3
    
    test_imageId=Data_df.iloc[i,0]
    #test_imageId='01914baf2.jpg'
    test_img=np.array(
        Image.open(f"{Data_Dir}/train_v2/{test_imageId}"))
    
    
    print(test_img.shape)
    masks=get_masks(test_imageId,Data_df,test_img.shape[:-1])
    print(masks.shape)
    plt.imshow(test_img)
    boxes=get_boxes(masks)
    print(boxes)
    draw_boxes(boxes)
    plt.imshow(np.sum(masks,axis=0),alpha=0.5)
    plt.show()

